name: Pull Request
on:
  pull_request:
    types: [ opened ]
  issue_comment:
    types: [created]
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
    - name: Run PR stats
      uses: flowwer-dev/pull-request-stats@v1
      with:
        charts: true
        sort-by: 'REVIEWS'
  asana:
    runs-on: ubuntu-latest
    steps:
    - name: Add to Asana
      uses: insurify/github-asana-action@v1.0.1
      with:
        asana-pat: '1/1203305742020972:59fad82d78c1324adadaf77026010544'
        task-comment: '* Pull Request: '
        trigger-phrase: "\\*\\*Asana Task:\\*\\*"
